### PR TITLE
Adding lib path search

### PR DESCRIPTION
**Pull request by remche**
On Debian Strech I had to add the /usr/lib/x86_64-linux-gnu/ path.

### CODE REVIEW

**Comment by sciencectn** [comment]
Thanks! Just curious, how does your system know to include this path when linking? Does it show up in `ldconfig -v`, LD_LIBRARY_PATH, or LIBRARY_PATH?

I tried to use ldconfig and environment variables to catch special cases but it looks like it missed yours.

**Comment by remche** [comment]
Hi,
Just checked, and the path is shown by `ldconfig -v`. I can test further if needed.

**Comment by sciencectn** [comment]
Awesome, if you wouldn't mind, try these things: 
1. Remove `stderr=DEVNULL` from the argument list of subprocess.call in [get_all_paths()](https://github.com/sciencectn/cgal-bindings/blob/master/setup.py#L180) so we can see all the errors. 
2. print the value of `m.group(1)` just after [line 186.](https://github.com/sciencectn/cgal-bindings/blob/master/setup.py#L187). This should tell us whether my regex stuff is catching anything at all from ldconfig. 
3. Change `except OSError` to `except None` [here](https://github.com/sciencectn/cgal-bindings/blob/master/setup.py#L188) to get more output. Maybe it can't run the ldconfig command for some reason.

**Comment by remche** [comment]
Ok, I stated what happened : [in debian flavoured system, ldconfig is in /sbin, which is not added to user $PATH](http://www.pathname.com/fhs/pub/fhs-2.3.html#FTN.AEN1058).

That's why it cant be found by setup script when run by normal user.
I will do a new pull request soon to fix that and detect properly under debian&co.

**Pull request merged**
